title: Xiangqian Meng's Homepage
page-top-title: Xiangqian Meng
top-section-bg-text: SCHOOL OF OCEAN AND CIVL ENGINEERING
home-subtitle: Xiangqian Meng&ensp;|&ensp;孟祥乾
copyright-text: '&copy; Sen Li 2023-2024. All Rights Reserved.'
